name: Enforce Branch Naming Convention

on:
  push:
    branches:
      - "*"

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
          echo "Branch name: $BRANCH_NAME"
          if [[ "$BRANCH_NAME" == "official" || "$BRANCH_NAME" == "dev" ]]; then
            echo "Skipping branch naming check for '$BRANCH_NAME'."
            exit 0
          fi
          if ! [[ "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release)\/[a-zA-Z0-9._-]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention."
            exit 1
          fi
